- hosts: keystone_all
  roles:
  - os_keystone
  post_tasks:
  - name: Install capstone from source
    pip:
      name: "git+https://github.com/rackerlabs/capstone#egg=capstone"
      virtualenv: "{{ keystone_venv_bin | dirname }}"
      virtualenv_site_packages: "no"
      extra_args: "{{ pip_install_options|default('') }}"
    tags:
      - capstone
  - name: Create capstone dir
    file:
      path: /etc/capstone
      state: directory
      owner: keystone
    tags:
      - capstone
  - name: Drop capstone.conf
    config_template:
      src: capstone.conf
      dest: /etc/capstone/capstone.conf
      config_overrides: "{{ capstone_overrides|default({}) }}"
      config_type: ini
    tags:
      - capstone
  vars:
    keystone_venv_tag: "capstone-testing"
    keystone_venv_bin: "/openstack/venvs/keystone-{{ keystone_venv_tag }}/bin"
    keystone_git_install_branch: e1354474cc59c13d31a9df0a6a0e58c8d1241d49
    keystone_developer_mode: true
    keystone_database_enabled: false
    keystone_service_setup: false
    keystone_token_provider: capstone
    keystone_database_connection_string: none
    keystone_public_endpoint: "https://identity.api.rackspacecloud.com"
    keystone_service_adminuri: "https://identity.api.rackspacecloud.com"
    internal_lb_vip_address: localhost
    keystone_auth_admin_token: none
    keystone_rabbitmq_password: none
    galera_client_drop_config_file: false
    keystone_keystone_conf_overrides:
      auth:
        method: password
        password: capstone
